#!/bin/bash


# sudo apt install pandoc

time python3 renderer.py ca > resume_ca.md
#pandoc -V 'mainfont:tablaksh.ttf' -V geometry:margin=2cm resume_ca.md -o resume_ca.pdf
time pandoc -V geometry:margin=2cm resume_ca.md -o resume_ca.pdf